More Robust Tests for automatic tests of api routes
statistical-perceptions/demoAPI-v2 pull request #14
Opened 2021-10-19 18:18 UTC by Elvictor01

I have pushed some updates to the code in a way that allows for more robust tests. It follows the progression of POST tests to PUT tests, then we are able to GET(tests) what we have imputed in that iteration and finally DELETE(tests) the document/collection in the same iteration.

So we run through all the routes in an intentional manner that allows for all the components(routes) to work as a system(demo API).

Cheers.
@brownsarahm @ttogun

2021-11-02 08:10 UTC, Elvictor01 commented
@brownsarahm I have added more elaborate comments based on the different categories of tests.

2021-11-02 08:13 UTC, Elvictor01 commented
@brownsarahm Do you have any peculiarities you are expecting as regards the commenting structure of the code as I have followed the methods implemented in the codebase?

2021-11-02 14:48 UTC, brownsarahm requested changes
this level of comment detail is okay, but tests should also include assertions.  and then the comments will be like, "create a new collection and confirm  (expected respnse)" etc.

2021-11-09 18:17 UTC, brownsarahm approved these changes

2021-11-10 10:14 UTC, merged