Test updates
statistical-perceptions/demoAPI-v2 pull request #6
Opened 2021-02-01 15:44 UTC by Elvictor01

2021-02-01 15:50 UTC, Elvictor01 commented
This current PR contains tests for all the API routes and the server live test in the "test directory" and also a pytest implementation for one of the functions in the normalCurve.py file...  You can run these route tests using the command _npm test_.

2021-02-01 18:44 UTC, brownsarahm requested changes
please gitignore `*.pyc`

this needs comments throughout. '

please ignore anything else that is user-specific, lik i htink package-lock shouldn't be here. 

For future reference, best practice is to limit a PR to ~1 change. (eg only adding the tests, not chaning anything else, even versions)

2021-02-01 18:44 UTC, brownsarahm commented on .vscode/settings.json
> +    "python.pythonPath": "C:\\Users\\vikin\\anaconda3\\python.exe"
please gitignore this file

2021-02-01 18:44 UTC, brownsarahm commented on node_modules/mongodb/HISTORY.md
> +## [3.6.3](https://github.com/mongodb/node-mongodb-native/compare/v3.6.1...v3.6.3) (2020-11-06)
why is this in our project?

2021-02-01 18:45 UTC, brownsarahm commented
@seanzhan0319 can you comment on the degree to which all of these files should be changed or if something weird happened?

2021-02-01 21:16 UTC, Elvictor01 commented on node_modules/mongodb/HISTORY.md
> +## [3.6.3](https://github.com/mongodb/node-mongodb-native/compare/v3.6.1...v3.6.3) (2020-11-06)
I think this is because i have an updated mongodb installed, and when I ran the initial npm install and consequently npm audit fix, there must have an update from my personal machine. I can downgrade my mongodb if that will work ma.

2021-02-01 21:21 UTC, Elvictor01 commented on .vscode/settings.json
> +    "python.pythonPath": "C:\\Users\\vikin\\anaconda3\\python.exe"
1. I would work on adding comments to the functional parts of the code
2. I would gitignore the corresponding .pyc files
3. I have removed the package.lock file

2021-02-04 23:36 UTC, seanzhan0319 commented
> @seanzhan0319 can you comment on the degree to which all of these files should be changed or if something weird happened?

these files look pretty good. I was able to run the tests locally, and the server seems to be working both locally and on heroku. 
Most of the tests seem to be testing the type of responses, for example, `res.body.should.be.a('object');` However, almost all responses are sent as JSON objects, and (I'm not sure if you were also thinking this but) we can test more than this. Specifically, we can look at each function, determine what it's returning, and test if it's returning what it's supposed to return. For example, if a function queries all the documents and returns a document that matches a given title, we can not only test if the response is an object but also test if the document's title actually matches the given title. Or, if a function deletes a document, we can check if the collection still contains the document after this function is executed. If the collection still contains the document, we will know our function is bad.

2021-02-05 00:01 UTC, brownsarahm approved these changes

2021-02-05 00:01 UTC, brownsarahm commented
lets merge these basic tests and I made Sean's comment a new issue about more compelte testing.

2021-02-23 10:27 UTC, merged